### ISSUE TITLE
Calculate the file size 

### ISSUE THREAD

**Issue by nabin98rana** [Pustakalaya/pustakalaya#102]

**Comment by bhoj001** [comment]
>>> import os
>>> b = os.path.getsize("/path/isa_005.mp3")
>>> b
2071611L

This code does the work it get the file size in bytes ,

For conversion of bytes to megabytes
 --> (1024*1024) bytes = 1 megabyte 

or
 X bytes  = X  / (1024 * 1024) megabytes

Link : 
https://stackoverflow.com/questions/2365100/converting-bytes-to-megabytes
https://stackoverflow.com/questions/2104080/how-to-check-file-size-in-python

**Comment by nix1947** [comment]
#103

**Comment by nix1947** [comment]
#103
